"""
Research Agent

Uses the planner output to search the web
and collect relevant research sources.
"""

from __future__ import annotations

import logging

from graph.state import ResearchState
from tools.search import search_web

logger = logging.getLogger(__name__)


def research_node(state: ResearchState) -> ResearchState:
    """
    Execute the research phase.

    Responsibilities:
    - Read keywords generated by the Planner.
    - Search the web.
    - Store the discovered sources in the shared state.

    Args:
        state: Current LangGraph state.

    Returns:
        Updated ResearchState.
    """

    planner = state.get("planner", {})

    keywords = planner.get("keywords", [])

    max_sources = planner.get("max_sources", 5)

    if isinstance(keywords, str):
        keywords = [keywords]

    if not isinstance(keywords, list):
        keywords = []

    try:
        max_sources = int(max_sources)
    except (TypeError, ValueError):
        max_sources = 5

    logger.info("Research Agent started.")

    sources = search_web(
        keywords=keywords,
        max_results=max_sources,
    )

    state.setdefault("research", {})

    state["research"]["sources"] = sources
    state["research"]["total_sources"] = len(sources)

    logger.info(
        "Research Agent collected %d sources.",
        len(sources),
    )

    return state
