"""
Pydantic models used by the Planner Agent.
"""

from typing import Literal

from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """
    Structured output generated by the Planner Agent.

    This object defines how the rest of the
    LangGraph workflow should execute.
    """

    complexity: Literal[
        "LOW",
        "MEDIUM",
        "HIGH",
    ] = Field(
        description="Estimated complexity of the user's query."
    )

    research_objective: str = Field(
        description="Primary objective of the research."
    )

    keywords: list[str] = Field(
        default_factory=list,
        description="Search keywords."
    )

    max_sources: int = Field(
        ge=1,
        le=15,
        description="Maximum number of web sources."
    )

    report_sections: list[str] = Field(
        default_factory=list,
        description="Suggested report outline."
    )